name: Bug Report
description: Report a bug with Skeld.net or its game modes
title: "[BUG] <Short description>"
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief description of the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Tell us how to make the bug happen.
      placeholder: |
        1. Start a game in Cops & Robbers
        2. Vent as Sheriff
        3. Game crashes
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: Game Mode / Feature
      options:
        - Vanilla (Skeld.net Base)
        - Zombie Mode
        - Cops & Robbers
        - Crazy Colors
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Game Version
      placeholder: "e.g. Among Us v2021.6.30s, Skeld.net Mod v3.1.0"
    validations:
      required: true

  - type: checkboxes
    id: platform
    attributes:
      label: Platform
      options:
        - label: Windows
        - label: Android
        - label: iOS
        - label: Other

  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: Add logs (from BepInEx/LogOutput.log), screenshots, or video if available.
      placeholder: Paste logs here or drag files when submitting the issue.

  - type: textarea
    id: extra
    attributes:
      label: Additional Info
      description: Any other context? Were you the host? Was it a one-time thing?
